[[SDL2_net]]
arch = "aarch64"
git-tree-sha1 = "39f9fa158b7d110e8d3b15b4a47deda1b06d0703"
os = "macos"

    [[SDL2_net.download]]
    sha256 = "6eee0dcfbc4224489d6744d25c4801bacebba3756e9ea0b62c3ca4b78d618ea7"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.aarch64-apple-darwin.tar.gz"
[[SDL2_net]]
arch = "aarch64"
git-tree-sha1 = "0f3784bcac532bb9c58d165c5f840ff0078d2b0c"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "c4e42d851839719d531a0b7c0eda7b3d800b6bb7a196562393f414f7cd5e2113"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.aarch64-linux-gnu.tar.gz"
[[SDL2_net]]
arch = "aarch64"
git-tree-sha1 = "6ef09e5a4653ecd95e4a0087bb4237cf00a1ad53"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "1ba0ea7e11a94b1fe196c28a030c1a985c7d797906c07bba54a555189e1c4f87"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.aarch64-linux-musl.tar.gz"
[[SDL2_net]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e4612ee6c1283138b3d8af770b196fce73a35bc"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "90f6b03db41d17506d70f03a41aa0be38afd472ec7de4c0c504416eee9d689b9"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.armv6l-linux-gnueabihf.tar.gz"
[[SDL2_net]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b92540761c2179110786c884c759ea60732a827b"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "4227cb5377436e30874463cac163e4a07e4cd5bdbfbf39163475cdab3db6c372"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.armv6l-linux-musleabihf.tar.gz"
[[SDL2_net]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a233bc3ade48426da5aee1e6934a03262db8931"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "e21f8fcc90c94c598299eb3cae33d8fc7fb4c319e2744951a9e39e7275f9b382"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[SDL2_net]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "80707a2cd5904e32711c7c35393193c365f87289"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "bade7ea146630bba3f6ed5bb48e336f3928cc07a637c143bc2b7dec8a99e1536"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[SDL2_net]]
arch = "i686"
git-tree-sha1 = "8dd45f46338a79e7d1c0eb08a53ecb72e000a9c0"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "216cd22b95dac69d23714b500a747dcea7bf09e8d3ab9c2d78a5443bf0dde245"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.i686-linux-gnu.tar.gz"
[[SDL2_net]]
arch = "i686"
git-tree-sha1 = "cc24c19fa2ff095ed1e3bc6b34eb3286a72561e0"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "306d9f5f8f3ac94f61404d20db424a3805853959e24cbb55e2e90c25ee2fec24"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.i686-linux-musl.tar.gz"
[[SDL2_net]]
arch = "i686"
git-tree-sha1 = "36d34aa3d52ec2d4070c27a25e183f7ccabbafab"
os = "windows"

    [[SDL2_net.download]]
    sha256 = "76cf57b7b09d6752013e512a332f39fa28d59e21d09a82e9c87f2b3f9d3e66f3"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.i686-w64-mingw32.tar.gz"
[[SDL2_net]]
arch = "powerpc64le"
git-tree-sha1 = "f83357406b8114548bf19e8af1a69a7fbda68c3d"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "897963d4d190f2327d7fc8c9e54fbd23360b2520f67249a82c7594b458dd2ca3"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "e0103f5e8f0afafb42ee7b08b0507dc42ca63442"
os = "macos"

    [[SDL2_net.download]]
    sha256 = "76575ba23cb91049c5044fd3cb288c745916a0e109c58ad2bc43a35c3b1e35b0"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.x86_64-apple-darwin.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "8b66f580e09a419b8bebd3da169bb3e2660d69f4"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "d24b4df908b4d366187e76cc11d30c8c9e617a57d004969cd5067d54d64c1625"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.x86_64-linux-gnu.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "8c7dc4add544e9668c98c1b2f57d13ca2737a6d5"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "dac133e7871ad3ee2e4c1bb2eee23e731c143d8bbd44c4e332c4be69c3ced117"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.x86_64-linux-musl.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "a83dcef10af6c2452c4d5bd5b917dc6ca830376c"
os = "freebsd"

    [[SDL2_net.download]]
    sha256 = "0bfcaa880065ba6f79625980209d921e869194775ac374d3d9ff1f6a6a322050"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "56b728479b6eda8bce98721aec24a6c1bd8f5a35"
os = "windows"

    [[SDL2_net.download]]
    sha256 = "dcaa91f5b94046669e2736db1e24de4b886c2fa4dc4bb136db122c7d788ca4c8"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.2.0+0/SDL2_net.v2.2.0.x86_64-w64-mingw32.tar.gz"
