[[SDL2_net]]
arch = "aarch64"
git-tree-sha1 = "35a7d02190908c7a02a9005dc87ce350484e0fbd"
os = "macos"

    [[SDL2_net.download]]
    sha256 = "a2570507c6277c1c38512513aa2b4ece65b1e501429bec75d0a1998b557d852d"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.aarch64-apple-darwin.tar.gz"
[[SDL2_net]]
arch = "aarch64"
git-tree-sha1 = "5fbd77cc59223e7d3bdc4d74fec44bef6438a642"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "5275d03a7d3cc3abe793f606cf6c70b46918beb3a1e09f60841931a49a339c91"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.aarch64-linux-gnu.tar.gz"
[[SDL2_net]]
arch = "aarch64"
git-tree-sha1 = "46fe9f01b6280af5916f8348ab35bda4a002e55f"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "7cc03cabb2b26394b0de19f2ea1e77a2cb427b2b57eaedf22078a25507d3c380"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.aarch64-linux-musl.tar.gz"
[[SDL2_net]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "57020ad9d68ffc94e1dafe68fff3810af2e90de8"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "ae147aef09fa07e69c13e940a9e8f11adfa5422b172060f9b9c6761f365ee090"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.armv6l-linux-gnueabihf.tar.gz"
[[SDL2_net]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "99f30bebf76f79e1b6514592f425d1cc9462f463"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "04e16b446acdb66d4a78d81e9a875934a89883de1d43f26bbb63a3b0c25856c4"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.armv6l-linux-musleabihf.tar.gz"
[[SDL2_net]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bf8c9d8c973a981a37a25685ae33da30ff29fe11"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "5af3414e13ee24c199b6cd71a1272cdc304e7f5a28414c00f10e3eb5a3a52cc4"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[SDL2_net]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d725489dd3699cc7cf2f54faff0a31fb3a1a007"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "12f2c1935c704a6a714ee321bc1bf604894b345b50fa924b5f3dba478c99e9f6"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[SDL2_net]]
arch = "i686"
git-tree-sha1 = "d2564567003318e1f298fefcbc5c87a27faba51c"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "94351fbea3720b8a807718905bbde7ef49109830b9aa4510083369a3b83c6dcf"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.i686-linux-gnu.tar.gz"
[[SDL2_net]]
arch = "i686"
git-tree-sha1 = "26539bdf247c5c785b513987cc52252eadaaa6e1"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "b1c89f831fdbaf243e763220774c1311aafca3d3d4b32aa348935eb45b963921"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.i686-linux-musl.tar.gz"
[[SDL2_net]]
arch = "i686"
git-tree-sha1 = "bad3dca9a109ea8a76bfab3fe6583bead147cbc8"
os = "windows"

    [[SDL2_net.download]]
    sha256 = "13cbe93d11394e78ab74dd447e29241049ce955c407e27264baacc7d7c17d215"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.i686-w64-mingw32.tar.gz"
[[SDL2_net]]
arch = "powerpc64le"
git-tree-sha1 = "86fe40c41adc79488a6e923611ca4a743f9c8f95"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "9c7c730a6da7fe3b80563250300c3eb580b2a2e2f8ed791873efc7f0f20fcbb1"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "a41c2da9535b617b17f8a6e50103faefc1762df0"
os = "macos"

    [[SDL2_net.download]]
    sha256 = "ab83b0fbfb2d8acfcf1fb00c21cf9bb31ac3eb381983e53240231fc576c06322"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.x86_64-apple-darwin.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "ab7cf1fb066f03bff8214e21b75d2368764965ee"
libc = "glibc"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "07688a2953af5edc5d1d88b86cfb16ffe95b1fed06366a6e97560fa04c24bbee"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.x86_64-linux-gnu.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "cbb59de3ff62203d88966a60b120bc2a1e3eadbc"
libc = "musl"
os = "linux"

    [[SDL2_net.download]]
    sha256 = "2bade1af7de6fcf3ad4c10958dc506bdc5ac97b957c59935ff8c97cfa4c88839"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.x86_64-linux-musl.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "e0aafd41e086bf96c61816b67cb3bd8848f7ba39"
os = "freebsd"

    [[SDL2_net.download]]
    sha256 = "ce31c771f49576278c48444310b7786d6d45230dbc52d4f7a98fe31358d3e1f4"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[SDL2_net]]
arch = "x86_64"
git-tree-sha1 = "54537624e03b175e7d3aba31e5e7d7cc0764fe2a"
os = "windows"

    [[SDL2_net.download]]
    sha256 = "4fad40b9c927748f83b857e12606cf36b7ba0cff8926268130a19a291b9e3b87"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_net_jll.jl/releases/download/SDL2_net-v2.0.1+0/SDL2_net.v2.0.1.x86_64-w64-mingw32.tar.gz"
