# Autogenerated wrapper script for SDL2_net_jll for x86_64-w64-mingw32
export libSDL2_net

using SDL2_jll
JLLWrappers.@generate_wrapper_header("SDL2_net")
JLLWrappers.@declare_library_product(libSDL2_net, "SDL2_net.dll")
function __init__()
    JLLWrappers.@generate_init_header(SDL2_jll)
    JLLWrappers.@init_library_product(
        libSDL2_net,
        "bin\\SDL2_net.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
